//GET http://localhost:3000/api/v1/cats
//POST http://localhost:3000/api/v1/cats

POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "name": "Whiskers",
  "username": "John Doe",
  "email": "2020-01-01",
  "password": "cat-photo.jpg"
}